import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

test('client socket bridge listens for generated state_update envelope', () => {
  const wsSource = readFileSync(new URL('../src/ws/orchestratorSocket.ts', import.meta.url), 'utf8');
  const pageSource = readFileSync(new URL('../src/app/page.tsx', import.meta.url), 'utf8');
  const replaySource = readFileSync(new URL('../src/app/replay/page.tsx', import.meta.url), 'utf8');
  const configSource = readFileSync(new URL('../src/lib/config.ts', import.meta.url), 'utf8');
  const connectionBridgeSource = readFileSync(
    new URL('../src/components/ConnectionBridge.tsx', import.meta.url),
    'utf8'
  );
  const sidePanelSource = readFileSync(new URL('../src/components/SidePanels.tsx', import.meta.url), 'utf8');
  const memoryPanelSource = readFileSync(new URL('../src/ui/MemoryPanel.tsx', import.meta.url), 'utf8');
  const godModeSource = readFileSync(new URL('../src/ui/GodModeMicPanel.tsx', import.meta.url), 'utf8');
  const trafficPanelSource = readFileSync(new URL('../src/ui/TrafficChartPanel.tsx', import.meta.url), 'utf8');
  const learningPanelSource = readFileSync(new URL('../src/ui/LearningPanel.tsx', import.meta.url), 'utf8');
  const vehiclePanelSource = readFileSync(new URL('../src/ui/VehicleCamPanel.tsx', import.meta.url), 'utf8');
  const citySource = readFileSync(new URL('../src/components/CityPlaceholder.tsx', import.meta.url), 'utf8');
  const mockWorldSource = readFileSync(new URL('../src/lib/mockWorld.ts', import.meta.url), 'utf8');
  const cssSource = readFileSync(new URL('../src/app/globals.css', import.meta.url), 'utf8');
  const typesSource = readFileSync(
    new URL('../../packages/shared-schemas/src/typescript/index.ts', import.meta.url),
    'utf8'
  );

  assert.match(wsSource, /aetherville:state_update/);
  assert.match(wsSource, /WorldStatePayload/);
  assert.match(wsSource, /transports: SocketTransport/);
  assert.match(configSource, /NEXT_PUBLIC_SOCKET_TRANSPORTS/);
  assert.match(configSource, /'polling'/);
  assert.match(connectionBridgeSource, /transport:/);
  assert.match(pageSource, /SidePanels/);
  assert.match(pageSource, /Replay fallback 열기/);
  assert.ok(pageSource.includes('href="/replay"'));
  assert.match(replaySource, /ReplayDriver/);
  assert.match(replaySource, /Live city로 돌아가기/);
  assert.match(sidePanelSource, /MemoryPanel/);
  assert.match(sidePanelSource, /VehicleCamPanel/);
  assert.match(sidePanelSource, /TrafficChartPanel/);
  assert.match(sidePanelSource, /LearningPanel/);
  assert.match(sidePanelSource, /GodModeMicPanel/);
  assert.match(memoryPanelSource, /MemoryRecord/);
  assert.match(godModeSource, /GodCommandResponse/);
  assert.match(godModeSource, /GodCommand/);
  assert.match(godModeSource, /commandPayload: GodCommand/);
  assert.match(godModeSource, /response\.ok/);
  assert.match(godModeSource, /aria-live="polite"/);
  assert.match(godModeSource, /Voice STT optional/);
  assert.match(godModeSource, /민지·민수 만남/);
  assert.match(godModeSource, /택시 호출/);
  assert.match(trafficPanelSource, /TrafficForecastPoint/);
  assert.match(trafficPanelSource, /trafficPanel-surge/);
  assert.match(learningPanelSource, /LearningSnapshot/);
  assert.match(learningPanelSource, /AI 학습 루프/);
  assert.match(learningPanelSource, /learningMetrics/);
  assert.match(vehiclePanelSource, /YoloDetection/);
  assert.match(vehiclePanelSource, /cameraBox/);
  assert.match(vehiclePanelSource, /Vehicle cam/);
  assert.match(citySource, /SceneLegend/);
  assert.match(citySource, /CitizenActor/);
  assert.match(citySource, /VehicleActor/);
  assert.match(citySource, /TrafficLightActor/);
  assert.match(citySource, /DroneActor/);
  assert.match(citySource, /GameCamera/);
  assert.match(citySource, /PedestrianRig/);
  assert.match(citySource, /VehicleWheel/);
  assert.match(citySource, /RainStreaks/);
  assert.match(citySource, /TrafficSurgeVehicles/);
  assert.match(citySource, /StreetProps/);
  assert.match(citySource, /ROAD_DASHES/);
  assert.match(citySource, /STREET_LIGHTS/);
  assert.match(citySource, /AnimatedActorGroup/);
  assert.match(citySource, /BillboardTag/);
  assert.match(citySource, /EventOverlays/);
  assert.match(citySource, /weatherOverlay-rain/);
  assert.match(citySource, /trafficSurgeOverlay/);
  assert.match(citySource, /ROAD_LINES/);
  assert.match(citySource, /BLOCK_CENTERS/);
  assert.match(citySource, /useFrame/);
  assert.match(citySource, /CITY_STAGE_SCALE = 1\.08/);
  assert.match(citySource, /CITY_CAMERA_FOV = 38/);
  assert.match(citySource, /택시·바퀴·헤드라이트/);
  assert.match(cssSource, /min-height: clamp\(560px, 78vh, 880px\)/);
  assert.match(cssSource, /grid-template-columns: repeat\(auto-fit, minmax\(220px, 1fr\)\)/);
  assert.match(cssSource, /@keyframes rainSheet/);
  assert.match(cssSource, /trafficPanel-surge/);
  assert.match(cssSource, /learningMetrics/);
  assert.match(cssSource, /learningMeter/);
  assert.match(cssSource, /MINI MAP/);
  assert.match(cssSource, /LIVE ACTORS/);
  assert.match(mockWorldSource, /poseOnRoute/);
  assert.match(mockWorldSource, /vehicleRoutes/);
  assert.match(mockWorldSource, /민지/);
  assert.match(mockWorldSource, /민수/);
  assert.match(mockWorldSource, /display_tags/);
  assert.match(mockWorldSource, /learning:/);
  assert.doesNotMatch(mockWorldSource, /Math\.sin\(angle/);
  assert.doesNotMatch(mockWorldSource, /Math\.cos\(angle/);
  assert.match(trafficPanelSource, /Traffic forecast/);
  assert.match(godModeSource, /God Mode/);
  assert.match(typesSource, /export interface SimStatusResponse/);
  assert.match(typesSource, /export interface GodCommandResponse/);
  assert.match(typesSource, /export interface LearningSnapshot/);
  assert.match(typesSource, /learning: LearningSnapshot/);
});
