import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

test('client socket bridge listens for generated state_update envelope', () => {
  const wsSource = readFileSync(new URL('../src/ws/orchestratorSocket.ts', import.meta.url), 'utf8');
  const pageSource = readFileSync(new URL('../src/app/page.tsx', import.meta.url), 'utf8');
  const replaySource = readFileSync(new URL('../src/app/replay/page.tsx', import.meta.url), 'utf8');
  const configSource = readFileSync(new URL('../src/lib/config.ts', import.meta.url), 'utf8');
  const connectionBridgeSource = readFileSync(
    new URL('../src/components/ConnectionBridge.tsx', import.meta.url),
    'utf8'
  );
  const sidePanelSource = readFileSync(new URL('../src/components/SidePanels.tsx', import.meta.url), 'utf8');
  const impactPanelSource = readFileSync(new URL('../src/ui/SceneImpactPanel.tsx', import.meta.url), 'utf8');
  const scenarioPanelSource = readFileSync(new URL('../src/ui/ScenarioDirectorPanel.tsx', import.meta.url), 'utf8');
  const memoryPanelSource = readFileSync(new URL('../src/ui/MemoryPanel.tsx', import.meta.url), 'utf8');
  const godModeSource = readFileSync(new URL('../src/ui/GodModeMicPanel.tsx', import.meta.url), 'utf8');
  const trafficPanelSource = readFileSync(new URL('../src/ui/TrafficChartPanel.tsx', import.meta.url), 'utf8');
  const learningPanelSource = readFileSync(new URL('../src/ui/LearningPanel.tsx', import.meta.url), 'utf8');
  const aiOperationsSource = readFileSync(new URL('../src/ui/AiOperationsPanel.tsx', import.meta.url), 'utf8');
  const vehiclePanelSource = readFileSync(new URL('../src/ui/VehicleCamPanel.tsx', import.meta.url), 'utf8');
  const citySource = readFileSync(new URL('../src/components/CityPlaceholder.tsx', import.meta.url), 'utf8');
  const mockWorldSource = readFileSync(new URL('../src/lib/mockWorld.ts', import.meta.url), 'utf8');
  const cssSource = readFileSync(new URL('../src/app/globals.css', import.meta.url), 'utf8');
  const typesSource = readFileSync(
    new URL('../../packages/shared-schemas/src/typescript/index.ts', import.meta.url),
    'utf8'
  );

  assert.match(wsSource, /aetherville:state_update/);
  assert.match(wsSource, /WorldStatePayload/);
  assert.match(wsSource, /transports: SocketTransport/);
  assert.match(configSource, /NEXT_PUBLIC_SOCKET_TRANSPORTS/);
  assert.match(configSource, /'polling'/);
  assert.match(connectionBridgeSource, /transport:/);
  assert.ok(connectionBridgeSource.includes('/api/v1/sim/start'));
  assert.match(pageSource, /SidePanels/);
  assert.match(pageSource, /force-dynamic/);
  assert.match(pageSource, /orchestratorUrl=\{config\.orchestratorUrl\}/);
  assert.match(pageSource, /Replay fallback 열기/);
  assert.ok(pageSource.includes('href="/replay"'));
  assert.match(replaySource, /ReplayDriver/);
  assert.match(replaySource, /orchestratorUrl=\{null\}/);
  assert.match(replaySource, /Live city로 돌아가기/);
  assert.match(sidePanelSource, /SceneImpactPanel/);
  assert.match(sidePanelSource, /ScenarioDirectorPanel/);
  assert.match(sidePanelSource, /AiOperationsPanel/);
  assert.match(sidePanelSource, /MemoryPanel/);
  assert.match(sidePanelSource, /VehicleCamPanel/);
  assert.match(sidePanelSource, /TrafficChartPanel/);
  assert.match(sidePanelSource, /LearningPanel/);
  assert.match(sidePanelSource, /GodModeMicPanel/);
  assert.match(sidePanelSource, /orchestratorUrl: string \| null/);
  assert.match(memoryPanelSource, /MemoryRecord/);
  assert.match(godModeSource, /GodCommandResponse/);
  assert.match(godModeSource, /GodCommand/);
  assert.match(godModeSource, /commandPayload: GodCommand/);
  assert.match(godModeSource, /response\.ok/);
  assert.match(godModeSource, /aria-live="polite"/);
  assert.match(godModeSource, /VoiceCommandResponse/);
  assert.match(godModeSource, /MediaRecorder/);
  assert.match(godModeSource, /Voice STT/);
  assert.match(godModeSource, /orchestratorUrl: string \| null/);
  assert.doesNotMatch(godModeSource, /process\.env\.NEXT_PUBLIC_ORCHESTRATOR_URL/);
  assert.match(godModeSource, /민지·민수 만남/);
  assert.match(godModeSource, /택시 호출/);
  assert.match(godModeSource, /연쇄 상황/);
  assert.match(trafficPanelSource, /TrafficForecastPoint/);
  assert.match(trafficPanelSource, /TrafficAiSnapshot/);
  assert.match(trafficPanelSource, /TrafficForecastAiSnapshot/);
  assert.match(trafficPanelSource, /trafficPanel-surge/);
  assert.match(trafficPanelSource, /GPU POLICY/);
  assert.match(trafficPanelSource, /LSTM FORECAST/);
  assert.match(impactPanelSource, /Live impact board/);
  assert.match(impactPanelSource, /buildImpactItems/);
  assert.match(impactPanelSource, /GPU POLICY/);
  assert.match(impactPanelSource, /LSTM FORECAST/);
  assert.match(impactPanelSource, /CITY AI/);
  assert.match(impactPanelSource, /SCENARIO/);
  assert.match(impactPanelSource, /worldState\.city_ai/);
  assert.match(impactPanelSource, /worldState\.scenario/);
  assert.match(impactPanelSource, /God Mode visible impact cards/);
  assert.match(scenarioPanelSource, /Scenario Director/);
  assert.match(scenarioPanelSource, /상황 실행 타임라인/);
  assert.match(scenarioPanelSource, /worldState\.scenario/);
  assert.match(scenarioPanelSource, /worldState\.task_graph/);
  assert.match(scenarioPanelSource, /TaskGraph/);
  assert.match(learningPanelSource, /LearningSnapshot/);
  assert.match(learningPanelSource, /AI 학습 루프/);
  assert.match(learningPanelSource, /learningMetrics/);
  assert.match(learningPanelSource, /Evolution state/);
  assert.match(learningPanelSource, /Policy promotion gate/);
  assert.match(learningPanelSource, /promotion-gated learning/);
  assert.match(learningPanelSource, /model-weight self-training: not verified/);
  assert.match(aiOperationsSource, /AI operations/);
  assert.match(aiOperationsSource, /Entity intent/);
  assert.match(aiOperationsSource, /Replan feed/);
  assert.match(aiOperationsSource, /Causal event chain/);
  assert.match(aiOperationsSource, /worldState\.entity_brains/);
  assert.match(aiOperationsSource, /worldState\.replans/);
  assert.match(vehiclePanelSource, /YoloDetection/);
  assert.match(vehiclePanelSource, /VehicleCameraFrame/);
  assert.match(vehiclePanelSource, /orchestratorUrl: string \| null/);
  assert.doesNotMatch(vehiclePanelSource, /getClientConfig/);
  assert.ok(vehiclePanelSource.includes('/api/v1/vehicles/'));
  assert.match(vehiclePanelSource, /REAL YOLO · RunPod 4090/);
  assert.match(vehiclePanelSource, /cameraBox/);
  assert.match(vehiclePanelSource, /Vehicle cam/);
  assert.match(citySource, /SceneLegend/);
  assert.match(citySource, /CitizenActor/);
  assert.match(citySource, /VehicleActor/);
  assert.match(citySource, /TrafficLightActor/);
  assert.match(citySource, /DroneActor/);
  assert.match(citySource, /GameCamera/);
  assert.match(citySource, /cityAiFocus/);
  assert.match(citySource, /scenarioFocus/);
  assert.match(citySource, /PedestrianRig/);
  assert.match(citySource, /VehicleWheel/);
  assert.match(citySource, /RainStreaks/);
  assert.match(citySource, /TrafficSurgeVehicles/);
  assert.match(citySource, /StreetProps/);
  assert.match(citySource, /ROAD_DASHES/);
  assert.match(citySource, /STREET_LIGHTS/);
  assert.match(citySource, /AnimatedActorGroup/);
  assert.match(citySource, /BillboardTag/);
  assert.match(citySource, /EventOverlays/);
  assert.match(citySource, /SceneDirectorHud/);
  assert.match(citySource, /SCENE DIRECTOR · LIVE IMPACT/);
  assert.match(citySource, /CITY AI PLAN/);
  assert.match(citySource, /SCENARIO RUNNING/);
  assert.match(citySource, /weatherOverlay-rain/);
  assert.match(citySource, /trafficSurgeOverlay/);
  assert.match(citySource, /ROAD_LINES/);
  assert.match(citySource, /BLOCK_CENTERS/);
  assert.match(citySource, /useFrame/);
  assert.match(citySource, /CITY_STAGE_SCALE = 1\.08/);
  assert.match(citySource, /CITY_CAMERA_FOV = 38/);
  assert.match(citySource, /택시·바퀴·헤드라이트/);
  assert.match(cssSource, /min-height: clamp\(560px, 78vh, 880px\)/);
  assert.match(cssSource, /grid-template-columns: repeat\(auto-fit, minmax\(220px, 1fr\)\)/);
  assert.match(cssSource, /@keyframes rainSheet/);
  assert.match(cssSource, /trafficPanel-surge/);
  assert.match(cssSource, /trafficAiBadge-active/);
  assert.match(cssSource, /learningMetrics/);
  assert.match(cssSource, /learningMeter/);
  assert.match(cssSource, /promotionGate/);
  assert.match(cssSource, /aiOperationsPanel/);
  assert.match(cssSource, /entityIntent/);
  assert.match(cssSource, /replanRecord/);
  assert.match(cssSource, /cameraModeBadge-real/);
  assert.match(cssSource, /directorHud/);
  assert.match(cssSource, /impactChip-active/);
  assert.match(cssSource, /scenarioPanel/);
  assert.match(cssSource, /scenarioStep-running/);
  assert.match(cssSource, /MINI MAP/);
  assert.match(cssSource, /LIVE ACTORS/);
  assert.match(mockWorldSource, /poseOnRoute/);
  assert.match(mockWorldSource, /vehicleRoutes/);
  assert.match(mockWorldSource, /민지/);
  assert.match(mockWorldSource, /민수/);
  assert.match(mockWorldSource, /display_tags/);
  assert.match(mockWorldSource, /traffic_ai:/);
  assert.match(mockWorldSource, /traffic_forecast_ai:/);
  assert.match(mockWorldSource, /learning:/);
  assert.match(mockWorldSource, /city_ai:/);
  assert.match(mockWorldSource, /scenario:/);
  assert.match(mockWorldSource, /task_graph:/);
  assert.match(mockWorldSource, /entity_brains:/);
  assert.match(mockWorldSource, /replans:/);
  assert.doesNotMatch(mockWorldSource, /Math\.sin\(angle/);
  assert.doesNotMatch(mockWorldSource, /Math\.cos\(angle/);
  assert.match(trafficPanelSource, /Traffic forecast/);
  assert.match(godModeSource, /God Mode/);
  assert.match(typesSource, /export interface SimStatusResponse/);
  assert.match(typesSource, /export interface GodCommandResponse/);
  assert.match(typesSource, /export interface TrafficAiSnapshot/);
  assert.match(typesSource, /export interface TrafficForecastAiSnapshot/);
  assert.match(typesSource, /export interface LearningSnapshot/);
  assert.match(typesSource, /export interface ScenarioDirective/);
  assert.match(typesSource, /export interface ScenarioStep/);
  assert.match(typesSource, /export interface TaskGraphPlan/);
  assert.match(typesSource, /export interface TaskGraphExecutionSnapshot/);
  assert.match(typesSource, /export interface EntityBrainState/);
  assert.match(typesSource, /export interface ReplanRecord/);
  assert.match(typesSource, /export interface EvolutionSnapshot/);
  assert.match(typesSource, /mode: 'mock' \\| 'real'/);
  assert.match(typesSource, /traffic_ai: TrafficAiSnapshot/);
  assert.match(typesSource, /traffic_forecast_ai: TrafficForecastAiSnapshot/);
  assert.match(typesSource, /learning: LearningSnapshot/);
  assert.ok(typesSource.includes('policy_candidates: PolicyCandidateSnapshot[]'));
  assert.match(typesSource, /promotion_gate: PolicyPromotionSnapshot/);
  assert.match(typesSource, /scenario\\?: ScenarioDirective \\| null/);
  assert.match(typesSource, /task_graph\\?: TaskGraphExecutionSnapshot \\| null/);
});
